### ISSUE TITLE
Post author card

### ISSUE THREAD

**Issue by Ed-wuard** [achique-luisdan/blog.achique.luisdan#17]
## creation of a publication footer

- [ ] create a post footer

**Comment by Ed-wuard** [comment]
## creation of a publication footer

- [x]  create a post footer completed :tada:

**Comment by achique-luisdan** [comment]
Excelente, entiendo la idea es crear una pequeña card o tarjeta con la información del autor invitado que escribió ese artículo.
Voy a crear una feature branch y convertir allí esta card en un componente de React.

**Comment by achique-luisdan** [comment]
[Ver código fuente](https://codi.link/PHNlY3Rpb24+DQogIDxkaXYgY2xhc3M9ImNhcmQtYXV0aG9yIj4NCiAgICAgIDxpbWcgY2xhc3M9ImNpcmNsZS1waG90byIgc3JjPSJodHRwczovL2FwaS5sb3JlbS5zcGFjZS9pbWFnZS9mYWNlP3c9NDAwJmg9NDAwIiBhbHQ9IkZvdG8gZGVsIGF1dG9yIGRlbCBhcnTDrWN1bG8iIC8+DQogICAgPGRpdj4NCiAgICAgIDxkaXYgY2xhc3M9ImNhcmQtaGVhZGVyIj4NCiAgICAgICAgPGg0Pk5hbWUgYW5kIFN1cm5hbWU8L2g0Pg0KICAgICAgICA8YSBocmVmPSIjIj48aW1nIHNyYz0iaHR0cHM6Ly9lbmNyeXB0ZWQtdGJuMC5nc3RhdGljLmNvbS9pbWFnZXM/cT10Ym46QU5kOUdjUkE3TGNGOF9ONlo5ang5Y3gxSU1XUWd0RG8tZ211aERjUVNRJnVzcXA9Q0FVIj48L2E+DQogICAgICA8L2Rpdj4NCiAgICAgIDxzcGFuPlByb2Zlc3Npb25hbCBSb2xlPC9zcGFuPg0KICAgICAgPHA+TG9yZW0sIGlwc3VtIGRvbG9yIHNpdCBhbWV0IGNvbnNlY3RldHVyIGFkaXBpc2ljaW5nIGVsaXQuIElsbG8gaXN0ZSBxdWlzcXVhbSBub24gYXQgcXVpYSByZXB1ZGlhbmRhZSBldW0gb3B0aW8NCiAgICAgICAgaGFydW0gbmloaWwsIHJlcGVsbGF0IGJlYXRhZSBhZCB2aXRhZSBzYXBpZW50ZSBlbGlnZW5kaSBzaW1pbGlxdWUgYWRpcGlzY2kgdm9sdXB0YXRpYnVzLiBFc3NlLCBlYXJ1bSEgTG9yZW0gaXBzdW0gZG9sb3Igc2l0IGFtZXQgY29uc2VjdGV0dXIsIGFkaXBpc2ljaW5nIGVsaXQuIEN1bXF1ZSBldmVuaWV0IHF1aSBmdWdhIGxhYm9yZSBhc3N1bWVuZGEgbWFnbmkgdGVuZXR1ciBhc3Blcm5hdHVyIGRlYml0aXMsIG5vbiBmYWNpbGlzLCBjdWxwYSB0ZW1wb3JpYnVzIGFjY3VzYW11cyBtb2RpIHJlcHVkaWFuZGFlIHF1b3MgYWxpcXVhbS4gVGVtcG9yYSwgZGljdGEgYWxpcXVhbS48L3A+DQogICAgPC9kaXY+DQogIDwvZGl2Pg0KPC9zZWN0aW9uPg==%7CKiB7DQogIG1hcmdpbjogMHB4Ow0KICBwYWRkaW5nOiAwcHg7DQogIGJveC1zaXppbmc6IGJvcmRlci1ib3g7DQogIGZvbnQtZmFtaWx5OiBBcmlhbCwgSGVsdmV0aWNhLCBzYW5zLXNlcmlmOw0KfQ0KLmNhcmQtYXV0aG9yIHsNCiAgZGlzcGxheTogZmxleDsNCiAgYWxpZ24taXRlbXM6IGNlbnRlcjsNCiAgZ2FwOiAyJTsNCiAgcGFkZGluZzogMiU7DQogIHBhZGRpbmctbGVmdDogOCU7DQogIHBhZGRpbmctcmlnaHQ6IDglOw0KfQ0KZGl2LmNhcmQtYXV0aG9yIGltZy5jaXJjbGUtcGhvdG8gew0KICBtYXgtd2lkdGg6IDE1JTsNCiAgbWFyZ2luOiAxJTsNCiAgYm9yZGVyLXJhZGl1czogMTAwJTsNCn0NCi5jYXJkLWhlYWRlciBpbWcgew0KICBtYXgtd2lkdGg6IDIwcHg7DQogIG1heC1oZWlnaHQ6IDIwcHg7DQp9DQouY2FyZC1oZWFkZXIgew0KICBkaXNwbGF5OiBmbGV4Ow0KICBhbGlnbi1pdGVtczogY2VudGVyOw0KfQ0KLmNhcmQtaGVhZGVyIGg0IHsNCiAgcGFkZGluZy1ib3R0b206IDEuNSU7DQp9DQouY2FyZC1oZWFkZXIgYSB7DQogIHRleHQtZGVjb3JhdGlvbjogbm9uZTsNCiAgbWFyZ2luLWxlZnQ6IDElOw0KICBwYWRkaW5nLWJvdHRvbTogMSU7DQp9DQouY2FyZC1hdXRob3Igc3BhbiB7DQogIGRpc3BsYXk6IGlubGluZS1ibG9jazsNCiAgZm9udC1zdHlsZTogaXRhbGljOw0KICBwYWRkaW5nLWJvdHRvbTogMSU7DQp9DQouY2FyZC1hdXRob3IgcCB7DQogIGxpbmUtaGVpZ2h0OiAyNHB4Ow0KfQ==%7C)

![CARD_AUTHOR](https://user-images.githubusercontent.com/46081094/221446706-e95c1775-d75c-41e0-bcb3-d6b3878c629f.png)

**Comment by achique-luisdan** [comment]
Para agregar un autor invitado al artículo anexar al encabezado las siguientes propiedades: 

```
authorName: 'Name and Surname'
authorPhoto: 'https://api.lorem.space/image/face?w=400&h=400'
authorLink: 'https://github.com/achique-luisdan'
authorRole: 'Professional Role'
authorResume: 'Lorem, ipsum dolor sit amet consectetur adipisicing elit. Illo iste quisquam non at quia repudiandae eum optio harum nihil, repellat beatae ad vitae sapiente eligendi similique adipisci voluptatibus. Esse, earum! Lorem ipsum dolor sit amet consectetur, adipisicing elit. Cumque eveniet qui fuga labore assumenda magni tenetur aspernatur debitis, non facilis, culpa temporibus accusamus modi repudiandae quos aliquam. Tempora, dicta aliquam.'"
```
